# Generated by Django 3.1.4 on 2021-06-04 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('PIN', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('group_name', models.CharField(max_length=60)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('group_members', models.ManyToManyField(blank=True, null=True, related_name='group_members', to=settings.AUTH_USER_MODEL)),
                ('group_moderators', models.ManyToManyField(blank=True, null=True, related_name='group_moderators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
