# Generated by Django 3.1.4 on 2021-06-04 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('complete', models.CharField(choices=[('UNINITIATED', 'UNINITIATED'), ('IN PROCESS', 'IN PROCESS'), ('READY', 'READY')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin_task', models.BooleanField(default=False)),
                ('group_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
