# Generated by Django 3.1.4 on 2021-04-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('tasks', '0006_auto_20210415_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
